; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
lib_deps = 
	paulstoffregen/Encoder@^1.4.4
	majicdesigns/MD_AD9833@^1.3.0
	pololu/PololuLedStrip@^4.3.1
test_framework = unity
test_build_src = true

[env:native]
platform = native
build_flags = 
    -D UNIT_TEST_NATIVE
    -include test/mock_arduino_for_native.h
test_build_src = true
; test_framework = unity ; Unity is often included directly by test files or discovered
; You might need to add lib_deps for Unity if not automatically handled
; by your test runner setup for native. For now, we assume test_async_morse.cpp includes it.
