; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
test_framework = unity
test_build_src = yes
build_flags = -D UNITY_OUTPUT_COLOR
test_ignore = 
	src/billboards_handler.cpp
	src/billboard.cpp
	test/billboard_test.cpp
	src/chime.cpp
	src/clock.cpp
	src/sleep_mode.cpp
	src/timer.cpp
	src/tools_mode.cpp
	src/idle_mode.cpp

[env]
test_framework = unity
test_build_src = yes
build_flags = -D UNITY_OUTPUT_COLOR
test_ignore = 
	src/billboards_handler.cpp
	src/billboard.cpp
	test/billboard_test.cpp
	src/chime.cpp
	src/clock.cpp
	src/sleep_mode.cpp
	src/timer.cpp
	src/tools_mode.cpp
	src/idle_mode.cpp

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
lib_deps = 
    paulstoffregen/Encoder@^1.4.4
    majicdesigns/MD_AD9833@^1.3.0
    pololu/PololuLedStrip@^4.3.1
	throwtheswitch/Unity@^2.6.0
	throwtheswitch/Unity@^2.6.0
    throwtheswitch/Unity@^2.6.0

; Test configuration
test_framework = unity
test_build_src = yes
